# Generated by Django 5.2.5 on 2025-09-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonks_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='ticker',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
