# Generated by Django 5.2.5 on 2025-09-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonks_app', '0002_alter_stock_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='purchase_date',
            field=models.DateField(),
        ),
    ]
